version: "3.4"

services:
  web:
    build: .
    image: jurglic/deps-api
    command: npm run start-dev
    environment:
      PORT: 3000
      REDIS_HOST: redis
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app:cached

  worker:
    build: .
    image: jurglic/deps-api
    command: npm run worker-dev
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app:cached
    environment:
      REDIS_HOST: redis

  redis:
    image: redis
