version: "3.4"

services:
  web:
    build: .
    command: npm run start-dev
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app:cached
